insert into allergy (allergy, name, icon) values (1, 'Groundplum Milkvetch', 'https://robohash.org/veletneque.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (2, 'Bushy Heliotrope', 'https://robohash.org/autemetquas.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (3, 'Widewing Springparsley', 'https://robohash.org/optioperspiciatispossimus.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (4, 'Crum''s Candle Snuffer Moss', 'https://robohash.org/odioexpeditaaperiam.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (5, 'Tropical Spiderflower', 'https://robohash.org/corruptidelectusveniam.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (6, 'Solomon''s Seal', 'https://robohash.org/adoloribuset.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (7, 'Witch''s Hair Lichen', 'https://robohash.org/sintsuntdolore.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (8, 'Adirondack Blackberry', 'https://robohash.org/eosquisquamet.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (9, 'Puerto Rico Philodendron', 'https://robohash.org/quasibeataeaut.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (10, 'Shameplant', 'https://robohash.org/voluptaseterror.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (11, 'American Chickweed', 'https://robohash.org/cupiditatenihilquo.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (12, 'Sparseflower Jewelflower', 'https://robohash.org/voluptatemtotamaliquam.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (13, 'Pale Phacelia', 'https://robohash.org/beataefugitrepellendus.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (14, 'Inchplant', 'https://robohash.org/enimmolestiaeullam.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (15, 'Creutzfeldt''s Cryptantha', 'https://robohash.org/placeatquovoluptatum.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (16, 'Yellow Honeysuckle', 'https://robohash.org/delectushicqui.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (17, 'Showy Phlox', 'https://robohash.org/eumipsaaut.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (18, 'Bashful Ragwort', 'https://robohash.org/dolorrepellatrem.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (19, 'Brewer''s Bittercress', 'https://robohash.org/maximeexcepturihic.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (20, 'Daltonia Moss', 'https://robohash.org/providentdeseruntquia.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (21, 'Royal Larkspur', 'https://robohash.org/ullamaliquidmagnam.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (22, 'Dwarf Birch', 'https://robohash.org/idvelquae.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (23, 'Wildginger', 'https://robohash.org/quiautemducimus.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (24, 'Bristly Buttercup', 'https://robohash.org/suntpraesentiumcum.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (25, 'Shortspike Noseburn', 'https://robohash.org/reprehenderitdoloresvoluptates.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (26, 'Wickes'' Loeskypnum Moss', 'https://robohash.org/enimestnemo.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (27, 'California Bedstraw', 'https://robohash.org/errorrerumet.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (28, 'Mt. Lassen Fleabane', 'https://robohash.org/utquisquibusdam.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (29, 'Cneoridium', 'https://robohash.org/odiocumdeleniti.png?size=30x30&set=set1');
insert into allergy (allergy, name, icon) values (30, 'Racomitrium Moss', 'https://robohash.org/voluptassapienteconsequatur.png?size=30x30&set=set1');
